version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PM_VERSION: ${PM_VERSION:-4.14.0}
    env_file:
      - .env
    ports:
      - "${PM_APP_PORT:-8081}:80"      # بیرون 8081 ← داخل 80
      - "${PM_BROADCASTER_PORT:-6001}:6001"   # در صورت نیاز به Echo/Broadcaster
    environment:
      - PM_APP_URL=${PM_APP_URL:-https://bpms.clickapps.ir}
    volumes:
      - storage:/var/www/html/storage
      # حالت توسعه: اگر می‌خواهی کد لوکال را هم Mount کنی (اختیاری)
      # - ./:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - pm

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - pm

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: processmaker
      MYSQL_USER: pm
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"   # اختیاری؛ اگر بیرون هم نیاز داری
    volumes:
      - database:/var/lib/mysql
    networks:
      - pm

volumes:
  database:
  storage:

networks:
  pm:
    driver: bridge
