version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # اگر در Dockerfile من از /usr/local/bin/init.sh استفاده کرده‌ایم:
    entrypoint: ["/usr/local/bin/init.sh"]
    ports:
      - "8081:80"           # دسترسی اپ روی http://localhost:8081
      - "6001:6001"         # (اختیاری) برای laravel-echo-server/broadcaster
    volumes:
      - ./:/var/www/html            # کد لوکال (حالت dev)
      - storage:/var/www/html/storage
      - vendor:/var/www/html/vendor
    depends_on:
      - mysql
      - redis
    networks:
      - pm

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - pm

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: processmaker
      MYSQL_USER: pm
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"    # (اختیاری) اگر بیرون کانتینر هم می‌خوای وصل شی
    volumes:
      - database:/var/lib/mysql
    networks:
      - pm

volumes:
  database:
  storage:
  vendor:

networks:
  pm:
    driver: bridge
