server {
    listen 80;
    server_name bpms.fararoo.clickapps.ir;

    # روت اصلی اپ ProcessMaker (Laravel/PHP)
    root /var/www/html/public;

    index index.php index.html;

    # لاگ‌ها
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # هندل فایل‌های استاتیک
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM (به کانتینر app)
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass pm-app:9000;   # نام سرویس app در docker-compose
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Laravel Echo Server (وب‌سوکت‌ها روی پورت 6001)
    location /socket.io/ {
        proxy_pass         http://pm-echo:6001;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "Upgrade";
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}
